name: "AWS Deploy to Beanstalk Environment"
description: "Deploy to AWS using AWS CLI parameters"
author: "Ricardo Lozano"
inputs:
  application_name:
    required: true
    description: "Elastic Beanstalk Application Name"
  environment_name:
    required: true
    description: "Elastic Beanstalk Environment Name"
  version_label:
    required: true
    description: "Version label to deploy"
  aws_region:
    required: true
    description: "AWS Region"
  s3_bucket:
    required: true
    description: "AWS S3 bucket for uploading app versions"
  application:
    required: true
    description: "Application's zip file path"
  wait:
    required: true
    description: "Wait time between status verification"

runs:
  # using: "docker"
  # image: docker://tihealth/aws-deploy-beanstalk:v1
  # args:
  #   - ${{ inputs.application_name }}
  #   - ${{ inputs.environment_name }}
  #   - ${{ inputs.version_label }}
  #   - ${{ inputs.aws_region }}
  #   - ${{ inputs.s3_bucket }}
  #   - ${{ inputs.application }}
  #   - ${{ inputs.wait }}
  using: "composite"
  steps:
    - run: |
        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker run tihealth/aws-deploy-beanstalk:v1 \
          ${{ inputs.application_name }} \
          ${{ inputs.environment_name }} \
          ${{ inputs.version_label }} \
          ${{ inputs.aws_region }} \
          ${{ inputs.s3_bucket }} \
          ${{ inputs.application }} \
          ${{ inputs.wait }}
      shell: bash
